### ISSUE TITLE
Sonderzeichen

### ISSUE THREAD

**Issue by SkiperTheBoss** [bichlepa/lang#1]
Es scheint Probleme zu geben wenn man bestimmte Sonderzeichen mit übersetzt, in meinem Beispiel unten soll ``&Save`tCtrg+S`` in ``&Speichern`tStrg+S`` übersetzt werden, scheint aber nicht zu funktionieren.

Test.ahk
```AutoHotkey
#SingleInstance force
#NoEnv

#Include language.ahk

_language:=Object()
_language.dir:=A_ScriptDir "\"

lang_init()

Menu, File, Add, % lang("&Open"), GuiClose
Menu, File, Add, % lang("Save`tCtrg+S"), GuiClose
Menu, File, Add, % lang("&Exit"), GuiClose

Menu, TopBar, Add, % lang("File"), :File
Gui, Menu, TopBar
Gui, Show, w200 h200, HELP

OnExit, Exit
return

GuiClose:
Exit:
ExitApp
```

en.ini
```ini
[language_info]
enname=English
name=English
[translations]
&Open=&Open
&Exit=&Exit
File=&File
Save`tCtrg+S=&Save`tCtrg+S
```

de.ini
```ini
[language_info]
enname=German
name=Deutsch
[translations]
&Open=&Öffnen
&Exit=&Beenden
File=&Datei
Save`tCtrg+S=&Speichern`tStrg+S
```

Eine super Idee die man noch hinzufügen könnte wäre das man mehre Übersetzungen für ein Wort hat und dann zBs. mit: `lang("&Save",2)` aufrufen könnte.

Dann wäre: `lang("&Save")` = `&Speichern`
Und das zweite `lang("&Save",2)` = `&Sparen`

Ansonsten super tolle Funktion.
LG Skiper

**Comment by bichlepa** [comment]
Hallo Skipper.

Das ``` `t ``` wird auch beim Zugriff in die .ini in einen Tabulator übersetzt. Wenn man die Zeile in der .ini Datei so anpasst, funktioniert es.
`Save	Ctrg+S=&Speichern	Strg+S` (Zwischen "Save" und "Ctrg" ist ein Tabulator)

Ich habe es allerdings nicht vorgesehen, dass der lang() Funktion Sonderzeichen übergeben werden. Der übergebene Text muss schließlich nie mit dem angezeigten Text übereinstimmen. Stattdessen empfehle ich dir das:
In der .ahk:
`lang("&Save (with Hotkey)")`
In de.ini:
`&Save (with Hotkey)=&&Speichern	Strg+S`

Wenn du doppeldeutige Begriffe übersetzen willst, dann kannst du z.B. sowas machen:
In der .ahk:
`lang("&Save (store)")`
`lang("&Save (economize)")`
Entsprechend in der en.ini:
```
&Save (store)=&Save
&Save (economize)=&Save
```
und in de.ini:
```
&Save (store)=&Speichern
&Save (economize)=&Sparen
```

**Comment by SkiperTheBoss** [comment]
Klasse! Vielen dank für die Hilfe.
